
## arg 1:  the new package version
post_install() {

  systemctl enable qubes-gui-agent.service 2> /dev/null

  sed -i '/^autospawn/d' /etc/pulse/client.conf
  echo autospawn=no >> /etc/pulse/client.conf

  # Remove pulseaudio autostart script
  echo "" > /etc/X11/xinit/xinitrc.d/pulseaudio

  # Then modify /etc/pacman.conf to ensure that this file won't be changed during upgrades. Add this line next to the commented NoUpgrade line:
  sed '/NoUpgrade/aNoUpgrade = /etc/X11/xinit/xinitrc.d/pulseaudio' -i /etc/pacman.conf

  ldconfig

  glib-compile-schemas /usr/share/glib-2.0/schemas &> /dev/null || :

}

post_upgrade() {

  ldconfig
  glib-compile-schemas /usr/share/glib-2.0/schemas &> /dev/null || :

}

## arg 1:  the old package version
pre_remove() {

  systemctl disable qubes-gui-agent.service

}

post_remove() {

  ldconfig
  glib-compile-schemas /usr/share/glib-2.0/schemas &> /dev/null || :

}

