# Imported from core-agent-linux
configure_pulseaudio() {
 
	sed -i '/^\(Not\|Only\)ShowIn/d' /etc/xdg/autostart/pulseaudio.desktop
	echo 'NotShowIn=QUBES;' >> /etc/xdg/autostart/pulseaudio.desktop

}

## arg 1:  the new package version
post_install() {

  systemctl enable qubes-gui-agent.service 2> /dev/null

  sed -i '/^autospawn/d' /etc/pulse/client.conf
  echo autospawn=no >> /etc/pulse/client.conf

  ldconfig

  echo "Fixing bug in xinitrc"
  # Archlinux specific: Fix potential bug in xinitrc making dbus to not initilize correctly
  sed 's:for f in /etc/X11/xinit/xinitrc.d/?\*\.sh:for f in /etc/X11/xinit/xinitrc.d/?\*:' -i /etc/X11/xinit/xinitrc

  echo "Configuring pulseaudio"
  configure_pulseaudio
}

post_upgrade() {
  post_install
}

## arg 1:  the old package version
pre_remove() {
  systemctl disable qubes-gui-agent.service
}

post_remove() {
  ldconfig
}

