#!/bin/sh
DISPLAY_XEPHYR="$1"

#LD_PRELOAD=/usr/lib64/qubes-gui-daemon/shmoverride.so /usr/bin/Xephyr -fullscreen "$DISPLAY_XEPHYR" > ~/.xephyr-errors.log 2>&1
LD_PRELOAD=/usr/lib64/qubes-gui-daemon/shmoverride.so /usr/bin/Xephyr -screen 1600x1200 "$DISPLAY_XEPHYR" > ~/.xephyr-errors 2>&1